/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyFoodLog {
  'entries' : Array<FoodLogEntry>,
  'timestamp' : Time,
}
export interface DailyWaterIntake {
  'entries' : Array<WaterIntakeEntry>,
  'timestamp' : Time,
}
export interface FoodItem {
  'fat' : number,
  'fiber' : number,
  'carbs' : number,
  'name' : string,
  'sugar' : number,
  'servingSize' : number,
  'servingUnit' : string,
  'caloriesPer100g' : number,
  'category' : string,
  'protein' : number,
}
export interface FoodLogEntry {
  'date' : Time,
  'quantity' : number,
  'mealType' : MealType,
  'foodName' : string,
}
export interface HealthMetrics {
  'weight' : number,
  'steps' : bigint,
  'heartRate' : number,
  'timestamp' : Time,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterIntakeEntry { 'glasses' : bigint, 'timestamp' : Time }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[FoodItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFoodItem' : ActorMethod<[string], undefined>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllFoodLogs' : ActorMethod<[Principal], Array<DailyFoodLog>>,
  'getAllHealthMetrics' : ActorMethod<[Principal], Array<HealthMetrics>>,
  'getAllWaterIntake' : ActorMethod<[Principal], Array<DailyWaterIntake>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoodByCategory' : ActorMethod<[string], Array<FoodItem>>,
  'getFoodLogsForDate' : ActorMethod<[Time], Array<DailyFoodLog>>,
  'getHealthMetricsForDate' : ActorMethod<[Time], Array<HealthMetrics>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaterIntakeForDate' : ActorMethod<[Time], Array<DailyWaterIntake>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logFoodEntry' : ActorMethod<[FoodLogEntry], undefined>,
  'logHealthMetrics' : ActorMethod<[HealthMetrics], undefined>,
  'logWaterIntake' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFoodByName' : ActorMethod<[string], Array<FoodItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];