/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'message' : string,
  'targetGoal' : AnnouncementTarget,
}
export type AnnouncementTarget = { 'all' : null } |
  { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null };
export interface Article {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'imageUrl' : string,
  'category' : string,
}
export interface DailyCheckIn {
  'waterGlasses' : bigint,
  'date' : string,
  'exercisesDone' : string,
  'dietNotes' : string,
  'sleepHours' : number,
}
export interface DailyFoodLog {
  'entries' : Array<FoodLogEntry>,
  'timestamp' : Time,
}
export interface DailyWaterIntake {
  'entries' : Array<WaterIntakeEntry>,
  'timestamp' : Time,
}
export interface DietPlan {
  'id' : bigint,
  'proteinTarget' : number,
  'goalType' : ProfileGoal,
  'name' : string,
  'fatTarget' : number,
  'description' : string,
  'mealTimingSuggestions' : Array<string>,
  'recommendedFoods' : Array<string>,
  'dailyCalorieTarget' : number,
  'carbsTarget' : number,
}
export interface FoodItem {
  'fat' : number,
  'region' : string,
  'fiber' : number,
  'carbs' : number,
  'name' : string,
  'sugar' : number,
  'servingSize' : number,
  'servingUnit' : string,
  'caloriesPer100g' : number,
  'category' : string,
  'protein' : number,
}
export interface FoodLogEntry {
  'date' : Time,
  'quantity' : number,
  'mealType' : MealType,
  'foodName' : string,
}
export interface FoodSuggestion {
  'status' : FoodSuggestionStatus,
  'submittedBy' : Principal,
  'timestamp' : Time,
  'foodItem' : FoodItem,
}
export type FoodSuggestionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface HealthMetrics {
  'weight' : number,
  'steps' : bigint,
  'heartRate' : number,
  'timestamp' : Time,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export type ProfileGoal = { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintenance' : null };
export type ReportStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'dismissed' : null };
export interface Review {
  'text' : string,
  'authorName' : string,
  'reviewType' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'heightCm' : number,
  'goal' : [] | [ProfileGoal],
  'name' : string,
  'weightKg' : number,
  'gender' : [] | [string],
  'phone' : string,
}
export interface UserReport {
  'id' : bigint,
  'status' : ReportStatus,
  'targetFoodName' : [] | [string],
  'createdAt' : Time,
  'description' : string,
  'reportType' : string,
  'reportedBy' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterIntakeEntry { 'glasses' : bigint, 'timestamp' : Time }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[FoodItem], undefined>,
  'approveFoodSuggestion' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], bigint>,
  'createArticle' : ActorMethod<[Article], bigint>,
  'createDietPlan' : ActorMethod<[DietPlan], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'deleteDietPlan' : ActorMethod<[bigint], undefined>,
  'deleteFoodItem' : ActorMethod<[string], undefined>,
  'deleteUserAccount' : ActorMethod<[Principal], undefined>,
  'dismissReport' : ActorMethod<[bigint], undefined>,
  'flagUser' : ActorMethod<[Principal, string], undefined>,
  'getActiveAnnouncementsForGoal' : ActorMethod<
    [[] | [ProfileGoal]],
    Array<Announcement>
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllCheckIns' : ActorMethod<[Principal], Array<DailyCheckIn>>,
  'getAllDietPlans' : ActorMethod<[], Array<DietPlan>>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllFoodLogs' : ActorMethod<[Principal], Array<DailyFoodLog>>,
  'getAllHealthMetrics' : ActorMethod<[Principal], Array<HealthMetrics>>,
  'getAllReports' : ActorMethod<[], Array<UserReport>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUsersCheckIns' : ActorMethod<
    [],
    Array<[Principal, Array<DailyCheckIn>]>
  >,
  'getAllWaterIntake' : ActorMethod<[Principal], Array<DailyWaterIntake>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInsForDate' : ActorMethod<[string], Array<DailyCheckIn>>,
  'getDietPlansByGoal' : ActorMethod<[ProfileGoal], Array<DietPlan>>,
  'getFlaggedUsers' : ActorMethod<[], Array<[Principal, string]>>,
  'getFoodByCategory' : ActorMethod<[string], Array<FoodItem>>,
  'getFoodByMacronutrients' : ActorMethod<
    [number, number, number],
    Array<FoodItem>
  >,
  'getFoodByName' : ActorMethod<[string], [] | [FoodItem]>,
  'getFoodByRegion' : ActorMethod<[string], Array<FoodItem>>,
  'getFoodLogsForDate' : ActorMethod<[Time], Array<DailyFoodLog>>,
  'getHealthMetricsForDate' : ActorMethod<[Time], Array<HealthMetrics>>,
  'getPendingFoodSuggestions' : ActorMethod<[], Array<FoodSuggestion>>,
  'getPublicReviews' : ActorMethod<[], Array<Review>>,
  'getUserJoinTimes' : ActorMethod<[], Array<[Principal, Time]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaterIntakeForDate' : ActorMethod<[Time], Array<DailyWaterIntake>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logFoodEntry' : ActorMethod<[FoodLogEntry], undefined>,
  'logHealthMetrics' : ActorMethod<[HealthMetrics], undefined>,
  'logWaterIntake' : ActorMethod<[bigint], undefined>,
  'rejectFoodSuggestion' : ActorMethod<[bigint], undefined>,
  'removeFoodLogEntry' : ActorMethod<[Time], undefined>,
  'resolveReport' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyCheckIn' : ActorMethod<[DailyCheckIn], undefined>,
  'searchFoodByName' : ActorMethod<[string], Array<FoodItem>>,
  'submitFoodSuggestion' : ActorMethod<[FoodItem], bigint>,
  'submitReview' : ActorMethod<[string, string, string], undefined>,
  'submitUserReport' : ActorMethod<[string, string, [] | [string]], bigint>,
  'toggleAnnouncement' : ActorMethod<[bigint], undefined>,
  'unflagUser' : ActorMethod<[Principal], undefined>,
  'updateAnnouncement' : ActorMethod<[Announcement], undefined>,
  'updateArticle' : ActorMethod<[Article], undefined>,
  'updateDietPlan' : ActorMethod<[DietPlan], undefined>,
  'updateFoodItem' : ActorMethod<[FoodItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];