/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodItem = IDL.Record({
  'fat' : IDL.Float64,
  'region' : IDL.Text,
  'fiber' : IDL.Float64,
  'carbs' : IDL.Float64,
  'name' : IDL.Text,
  'sugar' : IDL.Float64,
  'servingSize' : IDL.Float64,
  'servingUnit' : IDL.Text,
  'caloriesPer100g' : IDL.Float64,
  'category' : IDL.Text,
  'protein' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AnnouncementTarget = IDL.Variant({
  'all' : IDL.Null,
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
  'targetGoal' : AnnouncementTarget,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const ProfileGoal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const DietPlan = IDL.Record({
  'id' : IDL.Nat,
  'proteinTarget' : IDL.Float64,
  'goalType' : ProfileGoal,
  'name' : IDL.Text,
  'fatTarget' : IDL.Float64,
  'description' : IDL.Text,
  'mealTimingSuggestions' : IDL.Vec(IDL.Text),
  'recommendedFoods' : IDL.Vec(IDL.Text),
  'dailyCalorieTarget' : IDL.Float64,
  'carbsTarget' : IDL.Float64,
});
export const WeeklyMission = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'missionType' : IDL.Text,
  'xpReward' : IDL.Nat,
  'description' : IDL.Text,
  'targetCount' : IDL.Nat,
});
export const DailyCheckIn = IDL.Record({
  'waterGlasses' : IDL.Nat,
  'date' : IDL.Text,
  'exercisesDone' : IDL.Text,
  'dietNotes' : IDL.Text,
  'sleepHours' : IDL.Float64,
});
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const FoodLogEntry = IDL.Record({
  'date' : Time,
  'quantity' : IDL.Float64,
  'mealType' : MealType,
  'foodName' : IDL.Text,
});
export const DailyFoodLog = IDL.Record({
  'entries' : IDL.Vec(FoodLogEntry),
  'timestamp' : Time,
});
export const HealthMetrics = IDL.Record({
  'weight' : IDL.Float64,
  'steps' : IDL.Nat,
  'heartRate' : IDL.Float64,
  'timestamp' : Time,
});
export const PublicFoodWish = IDL.Record({
  'id' : IDL.Nat,
  'submitterPhone' : IDL.Text,
  'submitterName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'foodName' : IDL.Text,
  'reason' : IDL.Text,
});
export const PublicUserRecord = IDL.Record({
  'age' : IDL.Nat,
  'lastSeenAt' : IDL.Int,
  'heightCm' : IDL.Float64,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const UserReport = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReportStatus,
  'targetFoodName' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'reportType' : IDL.Text,
  'reportedBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'heightCm' : IDL.Float64,
  'goal' : IDL.Opt(ProfileGoal),
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const WaterIntakeEntry = IDL.Record({
  'glasses' : IDL.Nat,
  'timestamp' : Time,
});
export const DailyWaterIntake = IDL.Record({
  'entries' : IDL.Vec(WaterIntakeEntry),
  'timestamp' : Time,
});
export const FoodSuggestionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FoodSuggestion = IDL.Record({
  'status' : FoodSuggestionStatus,
  'submittedBy' : IDL.Principal,
  'timestamp' : Time,
  'foodItem' : FoodItem,
});
export const Review = IDL.Record({
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'reviewType' : IDL.Text,
  'timestamp' : Time,
});
export const WeeklyMissionProgress = IDL.Record({
  'weekKey' : IDL.Text,
  'completed' : IDL.Bool,
  'currentCount' : IDL.Nat,
  'missionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodItem' : IDL.Func([FoodItem], [], []),
  'approveFoodSuggestion' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
  'createArticle' : IDL.Func([Article], [IDL.Nat], []),
  'createDietPlan' : IDL.Func([DietPlan], [IDL.Nat], []),
  'createWeeklyMission' : IDL.Func([WeeklyMission], [IDL.Nat], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteCallerUserProfile' : IDL.Func([], [], []),
  'deleteDietPlan' : IDL.Func([IDL.Nat], [], []),
  'deleteFoodItem' : IDL.Func([IDL.Text], [], []),
  'deleteUserAccount' : IDL.Func([IDL.Principal], [], []),
  'dismissReport' : IDL.Func([IDL.Nat], [], []),
  'flagUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getActiveAnnouncementsForGoal' : IDL.Func(
      [IDL.Opt(ProfileGoal)],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllCheckIns' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyCheckIn)],
      ['query'],
    ),
  'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllFoodLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyFoodLog)],
      ['query'],
    ),
  'getAllHealthMetrics' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(HealthMetrics)],
      ['query'],
    ),
  'getAllPublicFoodWishes' : IDL.Func([], [IDL.Vec(PublicFoodWish)], ['query']),
  'getAllPublicUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PublicUserRecord))],
      ['query'],
    ),
  'getAllReports' : IDL.Func([], [IDL.Vec(UserReport)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllUsersCheckIns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DailyCheckIn)))],
      ['query'],
    ),
  'getAllWaterIntake' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyWaterIntake)],
      ['query'],
    ),
  'getAllWeeklyMissions' : IDL.Func([], [IDL.Vec(WeeklyMission)], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyCheckIn)],
      ['query'],
    ),
  'getDietPlansByGoal' : IDL.Func(
      [ProfileGoal],
      [IDL.Vec(DietPlan)],
      ['query'],
    ),
  'getFlaggedUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getFoodByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'getFoodByMacronutrients' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getFoodByName' : IDL.Func([IDL.Text], [IDL.Opt(FoodItem)], ['query']),
  'getFoodByRegion' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'getFoodLogsForDate' : IDL.Func([Time], [IDL.Vec(DailyFoodLog)], ['query']),
  'getHealthMetricsForDate' : IDL.Func(
      [Time],
      [IDL.Vec(HealthMetrics)],
      ['query'],
    ),
  'getPendingFoodSuggestions' : IDL.Func(
      [],
      [IDL.Vec(FoodSuggestion)],
      ['query'],
    ),
  'getPublicFoodWishCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPublicReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getPublicUser' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserRecord)],
      ['query'],
    ),
  'getPublicUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserJoinTimes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
      ['query'],
    ),
  'getUserMissionProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WeeklyMissionProgress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaterIntakeForDate' : IDL.Func(
      [Time],
      [IDL.Vec(DailyWaterIntake)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logFoodEntry' : IDL.Func([FoodLogEntry], [], []),
  'logHealthMetrics' : IDL.Func([HealthMetrics], [], []),
  'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
  'rejectFoodSuggestion' : IDL.Func([IDL.Nat], [], []),
  'removeFoodLogEntry' : IDL.Func([Time], [], []),
  'resolveReport' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
  'savePublicUser' : IDL.Func([IDL.Text, PublicUserRecord], [], []),
  'searchFoodByName' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'submitFoodSuggestion' : IDL.Func([FoodItem], [IDL.Nat], []),
  'submitPublicFoodWish' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitUserReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'toggleAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'unflagUser' : IDL.Func([IDL.Principal], [], []),
  'updateAnnouncement' : IDL.Func([Announcement], [], []),
  'updateArticle' : IDL.Func([Article], [], []),
  'updateDietPlan' : IDL.Func([DietPlan], [], []),
  'updateFoodItem' : IDL.Func([FoodItem], [], []),
  'updateMissionProgress' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodItem = IDL.Record({
    'fat' : IDL.Float64,
    'region' : IDL.Text,
    'fiber' : IDL.Float64,
    'carbs' : IDL.Float64,
    'name' : IDL.Text,
    'sugar' : IDL.Float64,
    'servingSize' : IDL.Float64,
    'servingUnit' : IDL.Text,
    'caloriesPer100g' : IDL.Float64,
    'category' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AnnouncementTarget = IDL.Variant({
    'all' : IDL.Null,
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
    'targetGoal' : AnnouncementTarget,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const ProfileGoal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const DietPlan = IDL.Record({
    'id' : IDL.Nat,
    'proteinTarget' : IDL.Float64,
    'goalType' : ProfileGoal,
    'name' : IDL.Text,
    'fatTarget' : IDL.Float64,
    'description' : IDL.Text,
    'mealTimingSuggestions' : IDL.Vec(IDL.Text),
    'recommendedFoods' : IDL.Vec(IDL.Text),
    'dailyCalorieTarget' : IDL.Float64,
    'carbsTarget' : IDL.Float64,
  });
  const WeeklyMission = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'missionType' : IDL.Text,
    'xpReward' : IDL.Nat,
    'description' : IDL.Text,
    'targetCount' : IDL.Nat,
  });
  const DailyCheckIn = IDL.Record({
    'waterGlasses' : IDL.Nat,
    'date' : IDL.Text,
    'exercisesDone' : IDL.Text,
    'dietNotes' : IDL.Text,
    'sleepHours' : IDL.Float64,
  });
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const FoodLogEntry = IDL.Record({
    'date' : Time,
    'quantity' : IDL.Float64,
    'mealType' : MealType,
    'foodName' : IDL.Text,
  });
  const DailyFoodLog = IDL.Record({
    'entries' : IDL.Vec(FoodLogEntry),
    'timestamp' : Time,
  });
  const HealthMetrics = IDL.Record({
    'weight' : IDL.Float64,
    'steps' : IDL.Nat,
    'heartRate' : IDL.Float64,
    'timestamp' : Time,
  });
  const PublicFoodWish = IDL.Record({
    'id' : IDL.Nat,
    'submitterPhone' : IDL.Text,
    'submitterName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'foodName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const PublicUserRecord = IDL.Record({
    'age' : IDL.Nat,
    'lastSeenAt' : IDL.Int,
    'heightCm' : IDL.Float64,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const UserReport = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReportStatus,
    'targetFoodName' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'reportType' : IDL.Text,
    'reportedBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'heightCm' : IDL.Float64,
    'goal' : IDL.Opt(ProfileGoal),
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const WaterIntakeEntry = IDL.Record({
    'glasses' : IDL.Nat,
    'timestamp' : Time,
  });
  const DailyWaterIntake = IDL.Record({
    'entries' : IDL.Vec(WaterIntakeEntry),
    'timestamp' : Time,
  });
  const FoodSuggestionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FoodSuggestion = IDL.Record({
    'status' : FoodSuggestionStatus,
    'submittedBy' : IDL.Principal,
    'timestamp' : Time,
    'foodItem' : FoodItem,
  });
  const Review = IDL.Record({
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'reviewType' : IDL.Text,
    'timestamp' : Time,
  });
  const WeeklyMissionProgress = IDL.Record({
    'weekKey' : IDL.Text,
    'completed' : IDL.Bool,
    'currentCount' : IDL.Nat,
    'missionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodItem' : IDL.Func([FoodItem], [], []),
    'approveFoodSuggestion' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
    'createArticle' : IDL.Func([Article], [IDL.Nat], []),
    'createDietPlan' : IDL.Func([DietPlan], [IDL.Nat], []),
    'createWeeklyMission' : IDL.Func([WeeklyMission], [IDL.Nat], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteCallerUserProfile' : IDL.Func([], [], []),
    'deleteDietPlan' : IDL.Func([IDL.Nat], [], []),
    'deleteFoodItem' : IDL.Func([IDL.Text], [], []),
    'deleteUserAccount' : IDL.Func([IDL.Principal], [], []),
    'dismissReport' : IDL.Func([IDL.Nat], [], []),
    'flagUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getActiveAnnouncementsForGoal' : IDL.Func(
        [IDL.Opt(ProfileGoal)],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllCheckIns' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllFoodLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyFoodLog)],
        ['query'],
      ),
    'getAllHealthMetrics' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(HealthMetrics)],
        ['query'],
      ),
    'getAllPublicFoodWishes' : IDL.Func(
        [],
        [IDL.Vec(PublicFoodWish)],
        ['query'],
      ),
    'getAllPublicUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PublicUserRecord))],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(UserReport)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllUsersCheckIns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DailyCheckIn)))],
        ['query'],
      ),
    'getAllWaterIntake' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyWaterIntake)],
        ['query'],
      ),
    'getAllWeeklyMissions' : IDL.Func([], [IDL.Vec(WeeklyMission)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getDietPlansByGoal' : IDL.Func(
        [ProfileGoal],
        [IDL.Vec(DietPlan)],
        ['query'],
      ),
    'getFlaggedUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getFoodByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'getFoodByMacronutrients' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getFoodByName' : IDL.Func([IDL.Text], [IDL.Opt(FoodItem)], ['query']),
    'getFoodByRegion' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'getFoodLogsForDate' : IDL.Func([Time], [IDL.Vec(DailyFoodLog)], ['query']),
    'getHealthMetricsForDate' : IDL.Func(
        [Time],
        [IDL.Vec(HealthMetrics)],
        ['query'],
      ),
    'getPendingFoodSuggestions' : IDL.Func(
        [],
        [IDL.Vec(FoodSuggestion)],
        ['query'],
      ),
    'getPublicFoodWishCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPublicReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getPublicUser' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserRecord)],
        ['query'],
      ),
    'getPublicUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserJoinTimes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
        ['query'],
      ),
    'getUserMissionProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WeeklyMissionProgress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaterIntakeForDate' : IDL.Func(
        [Time],
        [IDL.Vec(DailyWaterIntake)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logFoodEntry' : IDL.Func([FoodLogEntry], [], []),
    'logHealthMetrics' : IDL.Func([HealthMetrics], [], []),
    'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
    'rejectFoodSuggestion' : IDL.Func([IDL.Nat], [], []),
    'removeFoodLogEntry' : IDL.Func([Time], [], []),
    'resolveReport' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
    'savePublicUser' : IDL.Func([IDL.Text, PublicUserRecord], [], []),
    'searchFoodByName' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'submitFoodSuggestion' : IDL.Func([FoodItem], [IDL.Nat], []),
    'submitPublicFoodWish' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitUserReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'toggleAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'unflagUser' : IDL.Func([IDL.Principal], [], []),
    'updateAnnouncement' : IDL.Func([Announcement], [], []),
    'updateArticle' : IDL.Func([Article], [], []),
    'updateDietPlan' : IDL.Func([DietPlan], [], []),
    'updateFoodItem' : IDL.Func([FoodItem], [], []),
    'updateMissionProgress' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };