/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodItem = IDL.Record({
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'carbs' : IDL.Float64,
  'name' : IDL.Text,
  'sugar' : IDL.Float64,
  'servingSize' : IDL.Float64,
  'servingUnit' : IDL.Text,
  'caloriesPer100g' : IDL.Float64,
  'category' : IDL.Text,
  'protein' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyCheckIn = IDL.Record({
  'waterGlasses' : IDL.Nat,
  'date' : IDL.Text,
  'exercisesDone' : IDL.Text,
  'dietNotes' : IDL.Text,
  'sleepHours' : IDL.Float64,
});
export const Time = IDL.Int;
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const FoodLogEntry = IDL.Record({
  'date' : Time,
  'quantity' : IDL.Float64,
  'mealType' : MealType,
  'foodName' : IDL.Text,
});
export const DailyFoodLog = IDL.Record({
  'entries' : IDL.Vec(FoodLogEntry),
  'timestamp' : Time,
});
export const HealthMetrics = IDL.Record({
  'weight' : IDL.Float64,
  'steps' : IDL.Nat,
  'heartRate' : IDL.Float64,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'phone' : IDL.Text,
});
export const WaterIntakeEntry = IDL.Record({
  'glasses' : IDL.Nat,
  'timestamp' : Time,
});
export const DailyWaterIntake = IDL.Record({
  'entries' : IDL.Vec(WaterIntakeEntry),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodItem' : IDL.Func([FoodItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCallerUserProfile' : IDL.Func([], [], []),
  'deleteFoodItem' : IDL.Func([IDL.Text], [], []),
  'getAllCheckIns' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyCheckIn)],
      ['query'],
    ),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllFoodLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyFoodLog)],
      ['query'],
    ),
  'getAllHealthMetrics' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(HealthMetrics)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllUsersCheckIns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DailyCheckIn)))],
      ['query'],
    ),
  'getAllWaterIntake' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyWaterIntake)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyCheckIn)],
      ['query'],
    ),
  'getFoodByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'getFoodLogsForDate' : IDL.Func([Time], [IDL.Vec(DailyFoodLog)], ['query']),
  'getHealthMetricsForDate' : IDL.Func(
      [Time],
      [IDL.Vec(HealthMetrics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaterIntakeForDate' : IDL.Func(
      [Time],
      [IDL.Vec(DailyWaterIntake)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logFoodEntry' : IDL.Func([FoodLogEntry], [], []),
  'logHealthMetrics' : IDL.Func([HealthMetrics], [], []),
  'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
  'searchFoodByName' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodItem = IDL.Record({
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'carbs' : IDL.Float64,
    'name' : IDL.Text,
    'sugar' : IDL.Float64,
    'servingSize' : IDL.Float64,
    'servingUnit' : IDL.Text,
    'caloriesPer100g' : IDL.Float64,
    'category' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyCheckIn = IDL.Record({
    'waterGlasses' : IDL.Nat,
    'date' : IDL.Text,
    'exercisesDone' : IDL.Text,
    'dietNotes' : IDL.Text,
    'sleepHours' : IDL.Float64,
  });
  const Time = IDL.Int;
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const FoodLogEntry = IDL.Record({
    'date' : Time,
    'quantity' : IDL.Float64,
    'mealType' : MealType,
    'foodName' : IDL.Text,
  });
  const DailyFoodLog = IDL.Record({
    'entries' : IDL.Vec(FoodLogEntry),
    'timestamp' : Time,
  });
  const HealthMetrics = IDL.Record({
    'weight' : IDL.Float64,
    'steps' : IDL.Nat,
    'heartRate' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const WaterIntakeEntry = IDL.Record({
    'glasses' : IDL.Nat,
    'timestamp' : Time,
  });
  const DailyWaterIntake = IDL.Record({
    'entries' : IDL.Vec(WaterIntakeEntry),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodItem' : IDL.Func([FoodItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCallerUserProfile' : IDL.Func([], [], []),
    'deleteFoodItem' : IDL.Func([IDL.Text], [], []),
    'getAllCheckIns' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllFoodLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyFoodLog)],
        ['query'],
      ),
    'getAllHealthMetrics' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(HealthMetrics)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllUsersCheckIns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DailyCheckIn)))],
        ['query'],
      ),
    'getAllWaterIntake' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyWaterIntake)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getFoodByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'getFoodLogsForDate' : IDL.Func([Time], [IDL.Vec(DailyFoodLog)], ['query']),
    'getHealthMetricsForDate' : IDL.Func(
        [Time],
        [IDL.Vec(HealthMetrics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaterIntakeForDate' : IDL.Func(
        [Time],
        [IDL.Vec(DailyWaterIntake)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logFoodEntry' : IDL.Func([FoodLogEntry], [], []),
    'logHealthMetrics' : IDL.Func([HealthMetrics], [], []),
    'logWaterIntake' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
    'searchFoodByName' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };