/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PublicFoodWish {
    id: bigint;
    submitterPhone: string;
    submitterName: string;
    submittedAt: bigint;
    description: string;
    category: string;
    foodName: string;
    reason: string;
}
export interface UserProfile {
    heightCm: number;
    goal?: ProfileGoal;
    name: string;
    weightKg: number;
    gender?: string;
    phone: string;
}
export interface UserReport {
    id: bigint;
    status: ReportStatus;
    targetFoodName?: string;
    createdAt: Time;
    description: string;
    reportType: string;
    reportedBy: Principal;
}
export type Time = bigint;
export interface FoodLogEntry {
    date: Time;
    quantity: number;
    mealType: MealType;
    foodName: string;
}
export interface DailyWaterIntake {
    entries: Array<WaterIntakeEntry>;
    timestamp: Time;
}
export interface Article {
    id: bigint;
    title: string;
    body: string;
    createdAt: Time;
    imageUrl: string;
    category: string;
}
export interface HealthMetrics {
    weight: number;
    steps: bigint;
    heartRate: number;
    timestamp: Time;
}
export interface PublicUserRecord {
    age: bigint;
    lastSeenAt: bigint;
    heightCm: number;
    goal: string;
    name: string;
    joinedAt: bigint;
    weightKg: number;
    gender: string;
    phone: string;
}
export interface Announcement {
    id: bigint;
    title: string;
    createdAt: Time;
    isActive: boolean;
    message: string;
    targetGoal: AnnouncementTarget;
}
export interface WaterIntakeEntry {
    glasses: bigint;
    timestamp: Time;
}
export interface WeeklyMission {
    id: bigint;
    title: string;
    missionType: string;
    xpReward: bigint;
    description: string;
    targetCount: bigint;
}
export interface FoodSuggestion {
    status: FoodSuggestionStatus;
    submittedBy: Principal;
    timestamp: Time;
    foodItem: FoodItem;
}
export interface FoodItem {
    fat: number;
    region: string;
    fiber: number;
    carbs: number;
    name: string;
    sugar: number;
    servingSize: number;
    servingUnit: string;
    caloriesPer100g: number;
    category: string;
    protein: number;
}
export interface DietPlan {
    id: bigint;
    proteinTarget: number;
    goalType: ProfileGoal;
    name: string;
    fatTarget: number;
    description: string;
    mealTimingSuggestions: Array<string>;
    recommendedFoods: Array<string>;
    dailyCalorieTarget: number;
    carbsTarget: number;
}
export interface DailyFoodLog {
    entries: Array<FoodLogEntry>;
    timestamp: Time;
}
export interface DailyCheckIn {
    waterGlasses: bigint;
    date: string;
    exercisesDone: string;
    dietNotes: string;
    sleepHours: number;
}
export interface Review {
    text: string;
    authorName: string;
    reviewType: string;
    timestamp: Time;
}
export interface WeeklyMissionProgress {
    weekKey: string;
    completed: boolean;
    currentCount: bigint;
    missionId: bigint;
}
export enum AnnouncementTarget {
    all = "all",
    weightLoss = "weightLoss",
    muscleGain = "muscleGain",
    maintenance = "maintenance"
}
export enum FoodSuggestionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MealType {
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export enum ProfileGoal {
    weightLoss = "weightLoss",
    muscleGain = "muscleGain",
    maintenance = "maintenance"
}
export enum ReportStatus {
    resolved = "resolved",
    pending = "pending",
    dismissed = "dismissed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFoodItem(food: FoodItem): Promise<void>;
    approveFoodSuggestion(suggestionId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAnnouncement(announcement: Announcement): Promise<bigint>;
    createArticle(article: Article): Promise<bigint>;
    createDietPlan(plan: DietPlan): Promise<bigint>;
    createWeeklyMission(mission: WeeklyMission): Promise<bigint>;
    deleteAnnouncement(id: bigint): Promise<void>;
    deleteArticle(id: bigint): Promise<void>;
    deleteCallerUserProfile(): Promise<void>;
    deleteDietPlan(id: bigint): Promise<void>;
    deleteFoodItem(name: string): Promise<void>;
    deleteUserAccount(user: Principal): Promise<void>;
    dismissReport(id: bigint): Promise<void>;
    flagUser(user: Principal, reason: string): Promise<void>;
    getActiveAnnouncementsForGoal(goal: ProfileGoal | null): Promise<Array<Announcement>>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllArticles(): Promise<Array<Article>>;
    getAllCheckIns(user: Principal): Promise<Array<DailyCheckIn>>;
    getAllDietPlans(): Promise<Array<DietPlan>>;
    getAllFoodItems(): Promise<Array<FoodItem>>;
    getAllFoodLogs(user: Principal): Promise<Array<DailyFoodLog>>;
    getAllHealthMetrics(user: Principal): Promise<Array<HealthMetrics>>;
    getAllPublicFoodWishes(): Promise<Array<PublicFoodWish>>;
    getAllPublicUsers(): Promise<Array<[string, PublicUserRecord]>>;
    getAllReports(): Promise<Array<UserReport>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAllUsersCheckIns(): Promise<Array<[Principal, Array<DailyCheckIn>]>>;
    getAllWaterIntake(user: Principal): Promise<Array<DailyWaterIntake>>;
    getAllWeeklyMissions(): Promise<Array<WeeklyMission>>;
    getArticlesByCategory(category: string): Promise<Array<Article>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckInsForDate(date: string): Promise<Array<DailyCheckIn>>;
    getDietPlansByGoal(goalType: ProfileGoal): Promise<Array<DietPlan>>;
    getFlaggedUsers(): Promise<Array<[Principal, string]>>;
    getFoodByCategory(category: string): Promise<Array<FoodItem>>;
    getFoodByMacronutrients(minProtein: number, maxCarbs: number, maxFat: number): Promise<Array<FoodItem>>;
    getFoodByName(name: string): Promise<FoodItem | null>;
    getFoodByRegion(region: string): Promise<Array<FoodItem>>;
    getFoodLogsForDate(date: Time): Promise<Array<DailyFoodLog>>;
    getHealthMetricsForDate(date: Time): Promise<Array<HealthMetrics>>;
    getPendingFoodSuggestions(): Promise<Array<FoodSuggestion>>;
    getPublicFoodWishCount(): Promise<bigint>;
    getPublicReviews(): Promise<Array<Review>>;
    getPublicUser(deviceId: string): Promise<PublicUserRecord | null>;
    getPublicUserCount(): Promise<bigint>;
    getUserJoinTimes(): Promise<Array<[Principal, Time]>>;
    getUserMissionProgress(weekKey: string): Promise<Array<WeeklyMissionProgress>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWaterIntakeForDate(date: Time): Promise<Array<DailyWaterIntake>>;
    isCallerAdmin(): Promise<boolean>;
    logFoodEntry(entry: FoodLogEntry): Promise<void>;
    logHealthMetrics(metrics: HealthMetrics): Promise<void>;
    logWaterIntake(glasses: bigint): Promise<void>;
    rejectFoodSuggestion(suggestionId: bigint): Promise<void>;
    removeFoodLogEntry(entryTimestamp: Time): Promise<void>;
    resolveReport(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyCheckIn(checkIn: DailyCheckIn): Promise<void>;
    savePublicUser(deviceId: string, record: PublicUserRecord): Promise<void>;
    searchFoodByName(name: string): Promise<Array<FoodItem>>;
    submitFoodSuggestion(food: FoodItem): Promise<bigint>;
    submitPublicFoodWish(submitterName: string, submitterPhone: string, foodName: string, category: string, description: string, reason: string): Promise<bigint>;
    submitReview(authorName: string, text: string, reviewType: string): Promise<void>;
    submitUserReport(reportType: string, description: string, targetFoodName: string | null): Promise<bigint>;
    toggleAnnouncement(id: bigint): Promise<void>;
    unflagUser(user: Principal): Promise<void>;
    updateAnnouncement(announcement: Announcement): Promise<void>;
    updateArticle(article: Article): Promise<void>;
    updateDietPlan(plan: DietPlan): Promise<void>;
    updateFoodItem(food: FoodItem): Promise<void>;
    updateMissionProgress(missionId: bigint, weekKey: string, increment: bigint): Promise<void>;
}
import type { Announcement as _Announcement, AnnouncementTarget as _AnnouncementTarget, DailyFoodLog as _DailyFoodLog, DietPlan as _DietPlan, FoodItem as _FoodItem, FoodLogEntry as _FoodLogEntry, FoodSuggestion as _FoodSuggestion, FoodSuggestionStatus as _FoodSuggestionStatus, MealType as _MealType, ProfileGoal as _ProfileGoal, PublicUserRecord as _PublicUserRecord, ReportStatus as _ReportStatus, Time as _Time, UserProfile as _UserProfile, UserReport as _UserReport, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFoodItem(arg0: FoodItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodItem(arg0);
            return result;
        }
    }
    async approveFoodSuggestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFoodSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFoodSuggestion(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAnnouncement(arg0: Announcement): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(to_candid_Announcement_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(to_candid_Announcement_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createArticle(arg0: Article): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0);
            return result;
        }
    }
    async createDietPlan(arg0: DietPlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDietPlan(to_candid_DietPlan_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDietPlan(to_candid_DietPlan_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createWeeklyMission(arg0: WeeklyMission): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWeeklyMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWeeklyMission(arg0);
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteCallerUserProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerUserProfile();
            return result;
        }
    }
    async deleteDietPlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDietPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDietPlan(arg0);
            return result;
        }
    }
    async deleteFoodItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodItem(arg0);
            return result;
        }
    }
    async deleteUserAccount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserAccount(arg0);
            return result;
        }
    }
    async dismissReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReport(arg0);
            return result;
        }
    }
    async flagUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagUser(arg0, arg1);
            return result;
        }
    }
    async getActiveAnnouncementsForGoal(arg0: ProfileGoal | null): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAnnouncementsForGoal(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAnnouncementsForGoal(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllCheckIns(arg0: Principal): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCheckIns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCheckIns(arg0);
            return result;
        }
    }
    async getAllDietPlans(): Promise<Array<DietPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDietPlans();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDietPlans();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFoodItems(): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodItems();
            return result;
        }
    }
    async getAllFoodLogs(arg0: Principal): Promise<Array<DailyFoodLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodLogs(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodLogs(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHealthMetrics(arg0: Principal): Promise<Array<HealthMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHealthMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHealthMetrics(arg0);
            return result;
        }
    }
    async getAllPublicFoodWishes(): Promise<Array<PublicFoodWish>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicFoodWishes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicFoodWishes();
            return result;
        }
    }
    async getAllPublicUsers(): Promise<Array<[string, PublicUserRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicUsers();
            return result;
        }
    }
    async getAllReports(): Promise<Array<UserReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersCheckIns(): Promise<Array<[Principal, Array<DailyCheckIn>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersCheckIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersCheckIns();
            return result;
        }
    }
    async getAllWaterIntake(arg0: Principal): Promise<Array<DailyWaterIntake>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWaterIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWaterIntake(arg0);
            return result;
        }
    }
    async getAllWeeklyMissions(): Promise<Array<WeeklyMission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeeklyMissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeeklyMissions();
            return result;
        }
    }
    async getArticlesByCategory(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInsForDate(arg0: string): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInsForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInsForDate(arg0);
            return result;
        }
    }
    async getDietPlansByGoal(arg0: ProfileGoal): Promise<Array<DietPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietPlansByGoal(to_candid_ProfileGoal_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietPlansByGoal(to_candid_ProfileGoal_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlaggedUsers(): Promise<Array<[Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedUsers();
            return result;
        }
    }
    async getFoodByCategory(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodByCategory(arg0);
            return result;
        }
    }
    async getFoodByMacronutrients(arg0: number, arg1: number, arg2: number): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodByMacronutrients(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodByMacronutrients(arg0, arg1, arg2);
            return result;
        }
    }
    async getFoodByName(arg0: string): Promise<FoodItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodByName(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodByName(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodByRegion(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodByRegion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodByRegion(arg0);
            return result;
        }
    }
    async getFoodLogsForDate(arg0: Time): Promise<Array<DailyFoodLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodLogsForDate(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodLogsForDate(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthMetricsForDate(arg0: Time): Promise<Array<HealthMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthMetricsForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthMetricsForDate(arg0);
            return result;
        }
    }
    async getPendingFoodSuggestions(): Promise<Array<FoodSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFoodSuggestions();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFoodSuggestions();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicFoodWishCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicFoodWishCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicFoodWishCount();
            return result;
        }
    }
    async getPublicReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicReviews();
            return result;
        }
    }
    async getPublicUser(arg0: string): Promise<PublicUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUser(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUser(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUserCount();
            return result;
        }
    }
    async getUserJoinTimes(): Promise<Array<[Principal, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJoinTimes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJoinTimes();
            return result;
        }
    }
    async getUserMissionProgress(arg0: string): Promise<Array<WeeklyMissionProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMissionProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMissionProgress(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaterIntakeForDate(arg0: Time): Promise<Array<DailyWaterIntake>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaterIntakeForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaterIntakeForDate(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logFoodEntry(arg0: FoodLogEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logFoodEntry(to_candid_FoodLogEntry_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFoodEntry(to_candid_FoodLogEntry_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async logHealthMetrics(arg0: HealthMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logHealthMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logHealthMetrics(arg0);
            return result;
        }
    }
    async logWaterIntake(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWaterIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWaterIntake(arg0);
            return result;
        }
    }
    async rejectFoodSuggestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFoodSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFoodSuggestion(arg0);
            return result;
        }
    }
    async removeFoodLogEntry(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFoodLogEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFoodLogEntry(arg0);
            return result;
        }
    }
    async resolveReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveReport(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDailyCheckIn(arg0: DailyCheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyCheckIn(arg0);
            return result;
        }
    }
    async savePublicUser(arg0: string, arg1: PublicUserRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePublicUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePublicUser(arg0, arg1);
            return result;
        }
    }
    async searchFoodByName(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoodByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoodByName(arg0);
            return result;
        }
    }
    async submitFoodSuggestion(arg0: FoodItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFoodSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFoodSuggestion(arg0);
            return result;
        }
    }
    async submitPublicFoodWish(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPublicFoodWish(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPublicFoodWish(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async submitUserReport(arg0: string, arg1: string, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitUserReport(arg0, arg1, to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitUserReport(arg0, arg1, to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async toggleAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAnnouncement(arg0);
            return result;
        }
    }
    async unflagUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unflagUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unflagUser(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: Announcement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(to_candid_Announcement_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(to_candid_Announcement_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateArticle(arg0: Article): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0);
            return result;
        }
    }
    async updateDietPlan(arg0: DietPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDietPlan(to_candid_DietPlan_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDietPlan(to_candid_DietPlan_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFoodItem(arg0: FoodItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodItem(arg0);
            return result;
        }
    }
    async updateMissionProgress(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMissionProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMissionProgress(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AnnouncementTarget_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementTarget): AnnouncementTarget {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DailyFoodLog_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyFoodLog): DailyFoodLog {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_DietPlan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietPlan): DietPlan {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FoodLogEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodLogEntry): FoodLogEntry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_FoodSuggestionStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodSuggestionStatus): FoodSuggestionStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_FoodSuggestion_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodSuggestion): FoodSuggestion {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_MealType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealType): MealType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileGoal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileGoal): ProfileGoal {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserReport_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserReport): UserReport {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileGoal]): ProfileGoal | null {
    return value.length === 0 ? null : from_candid_ProfileGoal_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodItem]): FoodItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserRecord]): PublicUserRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: _Time;
    isActive: boolean;
    message: string;
    targetGoal: _AnnouncementTarget;
}): {
    id: bigint;
    title: string;
    createdAt: Time;
    isActive: boolean;
    message: string;
    targetGoal: AnnouncementTarget;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        isActive: value.isActive,
        message: value.message,
        targetGoal: from_candid_AnnouncementTarget_n15(_uploadFile, _downloadFile, value.targetGoal)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    proteinTarget: number;
    goalType: _ProfileGoal;
    name: string;
    fatTarget: number;
    description: string;
    mealTimingSuggestions: Array<string>;
    recommendedFoods: Array<string>;
    dailyCalorieTarget: number;
    carbsTarget: number;
}): {
    id: bigint;
    proteinTarget: number;
    goalType: ProfileGoal;
    name: string;
    fatTarget: number;
    description: string;
    mealTimingSuggestions: Array<string>;
    recommendedFoods: Array<string>;
    dailyCalorieTarget: number;
    carbsTarget: number;
} {
    return {
        id: value.id,
        proteinTarget: value.proteinTarget,
        goalType: from_candid_ProfileGoal_n20(_uploadFile, _downloadFile, value.goalType),
        name: value.name,
        fatTarget: value.fatTarget,
        description: value.description,
        mealTimingSuggestions: value.mealTimingSuggestions,
        recommendedFoods: value.recommendedFoods,
        dailyCalorieTarget: value.dailyCalorieTarget,
        carbsTarget: value.carbsTarget
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_FoodLogEntry>;
    timestamp: _Time;
}): {
    entries: Array<FoodLogEntry>;
    timestamp: Time;
} {
    return {
        entries: from_candid_vec_n25(_uploadFile, _downloadFile, value.entries),
        timestamp: value.timestamp
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    quantity: number;
    mealType: _MealType;
    foodName: string;
}): {
    date: Time;
    quantity: number;
    mealType: MealType;
    foodName: string;
} {
    return {
        date: value.date,
        quantity: value.quantity,
        mealType: from_candid_MealType_n28(_uploadFile, _downloadFile, value.mealType),
        foodName: value.foodName
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReportStatus;
    targetFoodName: [] | [string];
    createdAt: _Time;
    description: string;
    reportType: string;
    reportedBy: Principal;
}): {
    id: bigint;
    status: ReportStatus;
    targetFoodName?: string;
    createdAt: Time;
    description: string;
    reportType: string;
    reportedBy: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n33(_uploadFile, _downloadFile, value.status),
        targetFoodName: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.targetFoodName)),
        createdAt: value.createdAt,
        description: value.description,
        reportType: value.reportType,
        reportedBy: value.reportedBy
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm: number;
    goal: [] | [_ProfileGoal];
    name: string;
    weightKg: number;
    gender: [] | [string];
    phone: string;
}): {
    heightCm: number;
    goal?: ProfileGoal;
    name: string;
    weightKg: number;
    gender?: string;
    phone: string;
} {
    return {
        heightCm: value.heightCm,
        goal: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.goal)),
        name: value.name,
        weightKg: value.weightKg,
        gender: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.gender)),
        phone: value.phone
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FoodSuggestionStatus;
    submittedBy: Principal;
    timestamp: _Time;
    foodItem: _FoodItem;
}): {
    status: FoodSuggestionStatus;
    submittedBy: Principal;
    timestamp: Time;
    foodItem: FoodItem;
} {
    return {
        status: from_candid_FoodSuggestionStatus_n48(_uploadFile, _downloadFile, value.status),
        submittedBy: value.submittedBy,
        timestamp: value.timestamp,
        foodItem: value.foodItem
    };
}
function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
}): AnnouncementTarget {
    return "all" in value ? AnnouncementTarget.all : "weightLoss" in value ? AnnouncementTarget.weightLoss : "muscleGain" in value ? AnnouncementTarget.muscleGain : "maintenance" in value ? AnnouncementTarget.maintenance : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
}): ProfileGoal {
    return "weightLoss" in value ? ProfileGoal.weightLoss : "muscleGain" in value ? ProfileGoal.muscleGain : "maintenance" in value ? ProfileGoal.maintenance : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): MealType {
    return "breakfast" in value ? MealType.breakfast : "lunch" in value ? MealType.lunch : "snack" in value ? MealType.snack : "dinner" in value ? MealType.dinner : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    dismissed: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "pending" in value ? ReportStatus.pending : "dismissed" in value ? ReportStatus.dismissed : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): FoodSuggestionStatus {
    return "pending" in value ? FoodSuggestionStatus.pending : "approved" in value ? FoodSuggestionStatus.approved : "rejected" in value ? FoodSuggestionStatus.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietPlan>): Array<DietPlan> {
    return value.map((x)=>from_candid_DietPlan_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyFoodLog>): Array<DailyFoodLog> {
    return value.map((x)=>from_candid_DailyFoodLog_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodLogEntry>): Array<FoodLogEntry> {
    return value.map((x)=>from_candid_FoodLogEntry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserReport>): Array<UserReport> {
    return value.map((x)=>from_candid_UserReport_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodSuggestion>): Array<FoodSuggestion> {
    return value.map((x)=>from_candid_FoodSuggestion_n46(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementTarget_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementTarget): _AnnouncementTarget {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Announcement_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Announcement): _Announcement {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DietPlan_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietPlan): _DietPlan {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_FoodLogEntry_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodLogEntry): _FoodLogEntry {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_MealType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): _MealType {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileGoal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileGoal): _ProfileGoal {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileGoal | null): [] | [_ProfileGoal] {
    return value === null ? candid_none() : candid_some(to_candid_ProfileGoal_n9(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: Time;
    isActive: boolean;
    message: string;
    targetGoal: AnnouncementTarget;
}): {
    id: bigint;
    title: string;
    createdAt: _Time;
    isActive: boolean;
    message: string;
    targetGoal: _AnnouncementTarget;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        isActive: value.isActive,
        message: value.message,
        targetGoal: to_candid_AnnouncementTarget_n5(_uploadFile, _downloadFile, value.targetGoal)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Time;
    quantity: number;
    mealType: MealType;
    foodName: string;
}): {
    date: _Time;
    quantity: number;
    mealType: _MealType;
    foodName: string;
} {
    return {
        date: value.date,
        quantity: value.quantity,
        mealType: to_candid_MealType_n53(_uploadFile, _downloadFile, value.mealType),
        foodName: value.foodName
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm: number;
    goal?: ProfileGoal;
    name: string;
    weightKg: number;
    gender?: string;
    phone: string;
}): {
    heightCm: number;
    goal: [] | [_ProfileGoal];
    name: string;
    weightKg: number;
    gender: [] | [string];
    phone: string;
} {
    return {
        heightCm: value.heightCm,
        goal: value.goal ? candid_some(to_candid_ProfileGoal_n9(_uploadFile, _downloadFile, value.goal)) : candid_none(),
        name: value.name,
        weightKg: value.weightKg,
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    proteinTarget: number;
    goalType: ProfileGoal;
    name: string;
    fatTarget: number;
    description: string;
    mealTimingSuggestions: Array<string>;
    recommendedFoods: Array<string>;
    dailyCalorieTarget: number;
    carbsTarget: number;
}): {
    id: bigint;
    proteinTarget: number;
    goalType: _ProfileGoal;
    name: string;
    fatTarget: number;
    description: string;
    mealTimingSuggestions: Array<string>;
    recommendedFoods: Array<string>;
    dailyCalorieTarget: number;
    carbsTarget: number;
} {
    return {
        id: value.id,
        proteinTarget: value.proteinTarget,
        goalType: to_candid_ProfileGoal_n9(_uploadFile, _downloadFile, value.goalType),
        name: value.name,
        fatTarget: value.fatTarget,
        description: value.description,
        mealTimingSuggestions: value.mealTimingSuggestions,
        recommendedFoods: value.recommendedFoods,
        dailyCalorieTarget: value.dailyCalorieTarget,
        carbsTarget: value.carbsTarget
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileGoal): {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} {
    return value == ProfileGoal.weightLoss ? {
        weightLoss: null
    } : value == ProfileGoal.muscleGain ? {
        muscleGain: null
    } : value == ProfileGoal.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
} {
    return value == MealType.breakfast ? {
        breakfast: null
    } : value == MealType.lunch ? {
        lunch: null
    } : value == MealType.snack ? {
        snack: null
    } : value == MealType.dinner ? {
        dinner: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementTarget): {
    all: null;
} | {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintenance: null;
} {
    return value == AnnouncementTarget.all ? {
        all: null
    } : value == AnnouncementTarget.weightLoss ? {
        weightLoss: null
    } : value == AnnouncementTarget.muscleGain ? {
        muscleGain: null
    } : value == AnnouncementTarget.maintenance ? {
        maintenance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
